/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_xgsdk_client_CocosWrapper */
#ifndef _Included_com_xgsdk_client_CocosWrapper
#define _Included_com_xgsdk_client_CocosWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xgsdk_client_CocosWrapper
 * Method:    onResult
 * Signature: (Ljava/lang/String;)V
 */


JNIEXPORT void JNICALL Java_com_xgsdk_client_CocosWrapper_onResult
  (JNIEnv *, jclass, jstring);

void login_();

#ifdef __cplusplus
}
#endif
#endif
